# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TIs4AAQt.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TIsforAA(object):
    def setupUi(self, TIsforAA):
        TIsforAA.setObjectName("TIsforAA")
        TIsforAA.resize(972, 323)
        self.Select_all = QtWidgets.QPushButton(TIsforAA)
        self.Select_all.setGeometry(QtCore.QRect(811, 11, 85, 27))
        self.Select_all.setObjectName("Select_all")
        self.pushButton_5 = QtWidgets.QPushButton(TIsforAA)
        self.pushButton_5.setGeometry(QtCore.QRect(811, 44, 85, 27))
        self.pushButton_5.setObjectName("pushButton_5")
        self.layoutWidget = QtWidgets.QWidget(TIsforAA)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 9, 154, 297))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame = QtWidgets.QFrame(self.layoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.frame)
        self.spinBox.setMaximum(3)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 1, 0, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.frame)
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(4)
        self.spinBox_2.setProperty("value", 4)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout.addWidget(self.spinBox_2, 1, 1, 1, 1)
        self.verticalLayout_8.addWidget(self.frame)
        self.groupBox_5 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_13 = QtWidgets.QCheckBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_13.setFont(font)
        self.checkBox_13.setObjectName("checkBox_13")
        self.verticalLayout_3.addWidget(self.checkBox_13)
        self.checkBox_14 = QtWidgets.QCheckBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_14.setFont(font)
        self.checkBox_14.setObjectName("checkBox_14")
        self.verticalLayout_3.addWidget(self.checkBox_14)
        self.checkBox_15 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_15.setObjectName("checkBox_15")
        self.verticalLayout_3.addWidget(self.checkBox_15)
        self.checkBox_16 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_16.setObjectName("checkBox_16")
        self.verticalLayout_3.addWidget(self.checkBox_16)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_8.addWidget(self.groupBox_5)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.verticalLayout_11.addLayout(self.verticalLayout_9)
        self.layoutWidget1 = QtWidgets.QWidget(TIsforAA)
        self.layoutWidget1.setGeometry(QtCore.QRect(170, 10, 634, 283))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_2 = QtWidgets.QFrame(self.layoutWidget1)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.pseudoCalc = QtWidgets.QGroupBox(self.frame_2)
        self.pseudoCalc.setFlat(True)
        self.pseudoCalc.setCheckable(True)
        self.pseudoCalc.setChecked(False)
        self.pseudoCalc.setObjectName("pseudoCalc")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.pseudoCalc)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.pseudoCalc)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.PlainText)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.spinBox_4 = QtWidgets.QSpinBox(self.pseudoCalc)
        self.spinBox_4.setProperty("value", 10)
        self.spinBox_4.setObjectName("spinBox_4")
        self.horizontalLayout.addWidget(self.spinBox_4)
        self.verticalLayout.addWidget(self.pseudoCalc)
        self.verticalLayout_7.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.layoutWidget1)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_9.setFont(font)
        self.checkBox_9.setObjectName("checkBox_9")
        self.verticalLayout_2.addWidget(self.checkBox_9)
        self.checkBox_10 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_10.setObjectName("checkBox_10")
        self.verticalLayout_2.addWidget(self.checkBox_10)
        self.checkBox_11 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_11.setObjectName("checkBox_11")
        self.verticalLayout_2.addWidget(self.checkBox_11)
        self.checkBox_12 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_12.setObjectName("checkBox_12")
        self.verticalLayout_2.addWidget(self.checkBox_12)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.verticalLayout_7.addWidget(self.frame_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget1)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_4.addWidget(self.progressBar, 2, 0, 1, 2)
        self.tocalc = QtWidgets.QPushButton(self.layoutWidget1)
        self.tocalc.setObjectName("tocalc")
        self.gridLayout_4.addWidget(self.tocalc, 1, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.layoutWidget1)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 341, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_6.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_6.addWidget(self.checkBox_2)
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 56, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.spinBox_3 = QtWidgets.QSpinBox(self.frame_4)
        self.spinBox_3.setGeometry(QtCore.QRect(10, 130, 49, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_3.setFont(font)
        self.spinBox_3.setProperty("value", 30)
        self.spinBox_3.setObjectName("spinBox_3")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setGeometry(QtCore.QRect(80, 100, 56, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit.setGeometry(QtCore.QRect(80, 130, 51, 27))
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_4.addWidget(self.frame_4, 0, 0, 1, 2)
        self.horizontalLayout_2.addLayout(self.gridLayout_4)

        self.retranslateUi(TIsforAA)
        self.pushButton_5.clicked['bool'].connect(TIsforAA.close)
        QtCore.QMetaObject.connectSlotsByName(TIsforAA)

    def retranslateUi(self, TIsforAA):
        _translate = QtCore.QCoreApplication.translate
        TIsforAA.setWindowTitle(_translate("TIsforAA", "Topological Indexes for Amino acids"))
        self.Select_all.setText(_translate("TIsforAA", "Select all"))
        self.pushButton_5.setText(_translate("TIsforAA", "Close"))
        self.label.setText(_translate("TIsforAA", "Spaced"))
        self.label_2.setText(_translate("TIsforAA", "K-mers"))
        self.groupBox_5.setTitle(_translate("TIsforAA", "CTD"))
        self.checkBox_13.setText(_translate("TIsforAA", "C"))
        self.checkBox_14.setText(_translate("TIsforAA", "T"))
        self.checkBox_15.setText(_translate("TIsforAA", "D"))
        self.checkBox_16.setText(_translate("TIsforAA", "CTD"))
        self.label_3.setText(_translate("TIsforAA", "Pseudo amino acid composition"))
        self.pseudoCalc.setTitle(_translate("TIsforAA", "Calcule"))
        self.label_5.setText(_translate("TIsforAA", "Lamda"))
        self.groupBox_4.setTitle(_translate("TIsforAA", "Autocorrelation"))
        self.checkBox_9.setText(_translate("TIsforAA", "N-Moreau Broto"))
        self.checkBox_10.setText(_translate("TIsforAA", "Moran"))
        self.checkBox_11.setText(_translate("TIsforAA", "Geary"))
        self.checkBox_12.setText(_translate("TIsforAA", "Total"))
        self.tocalc.setText(_translate("TIsforAA", "Calcultate"))
        self.groupBox_2.setTitle(_translate("TIsforAA", "Sequence Order"))
        self.checkBox.setText(_translate("TIsforAA", "Coupling Number Total"))
        self.checkBox_2.setText(_translate("TIsforAA", "Quasi"))
        self.label_4.setText(_translate("TIsforAA", "Maxlag"))
        self.label_6.setText(_translate("TIsforAA", "Weight"))
        self.lineEdit.setText(_translate("TIsforAA", "0.1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TIsforAA = QtWidgets.QDialog()
    ui = Ui_TIsforAA()
    ui.setupUi(TIsforAA)
    TIsforAA.show()
    sys.exit(app.exec_())

